// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.get').default>>>>
    }
    '/api/hosts/:name': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hosts/[name].delete').default>>>>
    }
    '/api/hosts/:name/history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hosts/[name]/history.get').default>>>>
    }
    '/api/hosts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hosts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hosts/index.post').default>>>>
    }
    '/api/report': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/report.get').default>>>>
    }
    '/api/unknown': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unknown.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}