// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/19/2026, 7:49:12 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/hangjin/workspace/ipbook/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/plugins/**/*.{js,ts,mjs}","/home/hangjin/workspace/ipbook/composables/**/*.{js,ts,mjs}","/home/hangjin/workspace/ipbook/utils/**/*.{js,ts,mjs}","/home/hangjin/workspace/ipbook/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/hangjin/workspace/ipbook/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;